# Form implementation generated from reading ui file 'Forms\dannie.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1111, 743)
        self.tableView = QtWidgets.QTableView(parent=Dialog)
        self.tableView.setGeometry(QtCore.QRect(25, 50, 341, 611))
        self.tableView.setObjectName("tableView")
        self.tableView_2 = QtWidgets.QTableView(parent=Dialog)
        self.tableView_2.setGeometry(QtCore.QRect(385, 50, 341, 611))
        self.tableView_2.setObjectName("tableView_2")
        self.tableView_3 = QtWidgets.QTableView(parent=Dialog)
        self.tableView_3.setGeometry(QtCore.QRect(750, 50, 341, 611))
        self.tableView_3.setObjectName("tableView_3")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(70, 20, 251, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(420, 20, 261, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(810, 20, 221, 20))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Структура информации по грантам"))
        self.label_2.setText(_translate("Dialog", "Структура информации по конкурсам"))
        self.label_3.setText(_translate("Dialog", "Структура информации по ВУЗам"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
